# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Welcome to Colab!
"""

# =====================================
# 1. Import Libraries
# =====================================
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

# =====================================
# 2. Load Datasets (Upload in Colab first)
# =====================================
df_trans = pd.read_csv('/content/Retail_Data_Transactions.csv')
df_resp  = pd.read_csv('/content/Retail_Data_Response.csv')

# =====================================
# 3. Check Columns (IMPORTANT)
# =====================================
print("Transactions Columns:", df_trans.columns)
print("Response Columns:", df_resp.columns)

# =====================================
# 4. Fix Column Names (if needed)
# =====================================
# Make everything lowercase (safe)
df_trans.columns = df_trans.columns.str.lower()
df_resp.columns  = df_resp.columns.str.lower()

# =====================================
# 5. Merge Datasets
# =====================================
df = pd.merge(df_trans, df_resp, on='customer_id', how='left')

# =====================================
# 6. Fix 'response' column issue
# =====================================
# If response not present → create dummy
if 'response' not in df.columns:
    print("⚠️ 'response' column not found → creating dummy column")
    df['response'] = 0

# Fill missing response
df['response'] = df['response'].fillna(0)

# =====================================
# 7. Data Cleaning
# =====================================
df = df.dropna().copy()

# =====================================
# 8. Data Types
# =====================================
df['trans_date'] = pd.to_datetime(df['trans_date'], errors='coerce')
df['response'] = df['response'].astype(int)

# =====================================
# 9. Feature Engineering
# =====================================
df['month'] = df['trans_date'].dt.month
df['month_name'] = df['trans_date'].dt.month_name()

# =====================================
# 10. Outlier Removal (Z-score)
# =====================================
z = np.abs(stats.zscore(df['tran_amount']))
df = df[z < 3]

# =====================================
# 11. Monthly Sales (Bar Chart)
# =====================================
monthly_sales = df.groupby('month_name')['tran_amount'].sum().sort_values(ascending=False)

sns.barplot(x=monthly_sales.index, y=monthly_sales.values)
plt.xticks(rotation=45)
plt.title("Monthly Sales")
plt.show()

# =====================================
# 12. Time Series (Line Chart)
# =====================================
df['month_year'] = df['trans_date'].dt.to_period('M')
ts = df.groupby('month_year')['tran_amount'].sum()
ts.index = ts.index.to_timestamp()

plt.plot(ts.index, ts.values, marker='o')
plt.title("Monthly Sales Trend")
plt.xticks(rotation=45)
plt.show()

# =====================================
# 13. Top 5 Customers (Spending)
# =====================================
top_5 = df.groupby('customer_id')['tran_amount'].sum().reset_index()
top_5 = top_5.sort_values(by='tran_amount', ascending=False).head(5)

print("Top 5 Customer IDs:")
print(top_5['customer_id'].tolist())

# Line Chart
plt.plot(top_5['customer_id'], top_5['tran_amount'], marker='o')
plt.title("Top 5 Customers (Spending)")
plt.show()

# =====================================
# 14. Top Customers by Orders
# =====================================
orders = df.groupby('customer_id').size().reset_index(name='count')
orders = orders.sort_values(by='count', ascending=False).head(5)

sns.barplot(x='customer_id', y='count', data=orders)
plt.title("Top 5 Customers (Orders)")
plt.show()

# =====================================
# 15. Churn Analysis
# =====================================
latest_date = df['trans_date'].max()

churn_df = df.groupby('customer_id')['trans_date'].max().reset_index()
churn_df['recency'] = (latest_date - churn_df['trans_date']).dt.days

# 90 days rule
churn_df['status'] = churn_df['recency'].apply(lambda x: 'Churn' if x > 90 else 'Active')

print(churn_df['status'].value_counts())

sns.countplot(x='status', data=churn_df)
plt.title("Churn vs Active Customers")
plt.show()

# =====================================
# 16. KPI Metrics
# =====================================
print("Total Revenue:", df['tran_amount'].sum())
print("Total Orders:", df.shape[0])
print("Total Customers:", df['customer_id'].nunique())
print("Average Order Value:", df['tran_amount'].mean())

# =====================================
# 17. RFM Analysis
# =====================================
latest_date = df['trans_date'].max()

rfm = df.groupby('customer_id').agg({
    'trans_date': lambda x: (latest_date - x.max()).days,
    'customer_id': 'count',
    'tran_amount': 'sum'
})

rfm.columns = ['Recency', 'Frequency', 'Monetary']

print(rfm.head())